### ISSUE TITLE
Exception thrown when building wiki

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#182]
```
InvalidArgumentException from line 83 of /var/www/html/wikis/556438b9474447341a9c0cdba8015133/w/includes/libs/rdbms/database/domain/DatabaseDomain.php: Domain must be a string or Wikimedia\Rdbms\DatabaseDomain
#0 /var/www/html/wikis/556438b9474447341a9c0cdba8015133/w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(297): Wikimedia\Rdbms\DatabaseDomain::newFromId(NULL)
#1 /var/www/html/wikis/556438b9474447341a9c0cdba8015133/w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(276): Wikimedia\Rdbms\LoadBalancer->resolveDomainInstance(NULL)
#2 /var/www/html/wikis/556438b9474447341a9c0cdba8015133/w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(1042): Wikimedia\Rdbms\LoadBalancer->resolveDomainID(NULL)
#3 /var/www/html/wikis/556438b9474447341a9c0cdba8015133/w/extensions/OATHAuth/src/Hook/LoadExtensionSchemaUpdates/UpdateTables.php(95): Wikimedia\Rdbms\LoadBalancer->getConnectionRef(-2, Array, NULL)
#4 /var/www/html/wikis/556438b9474447341a9c0cdba8015133/w/includes/installer/DatabaseUpdater.php(532): MediaWiki\Extension\OATHAuth\Hook\LoadExtensionSchemaUpdates\UpdateTables->schemaUpdateOldUsersFromInstaller(Object(MysqlUpdater))
#5 /var/www/html/wikis/556438b9474447341a9c0cdba8015133/w/includes/installer/DatabaseUpdater.php(500): DatabaseUpdater->runUpdates(Array, true)
#6 /var/www/html/wikis/556438b9474447341a9c0cdba8015133/w/includes/installer/DatabaseInstaller.php(348): DatabaseUpdater->doUpdates(Array)
#7 /var/www/html/wikis/556438b9474447341a9c0cdba8015133/w/includes/installer/Installer.php(1723): DatabaseInstaller->createExtensionTables(Object(MysqlInstaller))
#8 /var/www/html/wikis/556438b9474447341a9c0cdba8015133/w/includes/installer/CliInstaller.php(211): Installer->performInstallation(Array, Array)
#9 /var/www/html/wikis/556438b9474447341a9c0cdba8015133/w/maintenance/install.php(140): CliInstaller->execute()
#10 /var/www/html/wikis/556438b9474447341a9c0cdba8015133/w/maintenance/doMaintenance.php(106): CommandLineInstaller->execute()
#11 /var/www/html/wikis/556438b9474447341a9c0cdba8015133/w/maintenance/install.php(201): require_once('/var/www/html/w...')
#12 {main}
```

**Comment by MatmaRex** [comment]
Caused by https://gerrit.wikimedia.org/r/c/mediawiki/core/+/641822

Looks like OATHAuth expects the value of `$wgOATHAuthDatabase` to be pulled in from extension.json, but that doesn't happen in the installer, and somehow nothing was failing before.

**Comment by MatmaRex** [comment]
You can probably just uncheck "mediawiki/extensions/OATHAuth" when making the wiki, I don't have time to look into this right now.

**Comment by edg2s** [comment]
CC @krinkle

**Comment by edg2s** [comment]
I'll see if I can disable OAuth on the server for now.

**Comment by Krinkle** [comment]
The check failing works as expected. Unless other impact, ignoring for now. It indeed does not appear to have been working previously either. From a quick look it seems OATHAuth appears to be using this hook to migrate old data, which isn't applicable to new installs. It should probaly either do nothing if the variable is unset, or it should otherwise ensure the function is never called in the first place.

**Comment by edg2s** [comment]
I've monkey-patched away the OAuth option on wmflabs:

```php
if ( $repo === 'mediawiki/extensions/OATHAuth' ) continue;
```

**Comment by edg2s** [comment]
This has been fixed upstream, I'll remove the patches.

**Comment by edg2s** [comment]
Done
