### ISSUE TITLE
Fatal error: Uncaught MediaWiki\OAuthClient\Exception: JWT has incorrect format

### ISSUE THREAD

**Issue by MatmaRex** [MatmaRex/patchdemo#232]
I just saw this error while viewing the main page. It worked fine after refreshing.

![image](https://user-images.githubusercontent.com/160413/106902791-80e03800-66f9-11eb-965d-ac77c4a1fa76.png)
```
Fatal error:  Uncaught MediaWiki\OAuthClient\Exception: JWT has incorrect format. Received: {"error":"mwoauth-oauth-exception","message":"An error occurred in the OAuth protocol: Nonce already used: 01a40493d4fbfa332b4d9ced52f2177f"} in /var/www/html/vendor/mediawiki/oauthclient/src/Client.php:327
Stack trace:
#0 /var/www/html/vendor/mediawiki/oauthclient/src/Client.php(199): MediaWiki\OAuthClient\Client->decodeJWT('{"error":"mwoau...', 'c2822ff10e5e2ac...')
#1 /var/www/html/oauth.php(42): MediaWiki\OAuthClient\Client->identify(Object(MediaWiki\OAuthClient\Token))
#2 /var/www/html/includes.php(49): include_once('/var/www/html/o...')
#3 /var/www/html/index.php(2): require_once('/var/www/html/i...')
#4 {main}
  thrown in /var/www/html/vendor/mediawiki/oauthclient/src/Client.php on line 327
```

**Comment by edg2s** [comment]
I saw this at some point too. Some sort of oauth expiry? Could’ve been triggered by something happening on meta. Haven’t touched that code recently.
