### ISSUE TITLE
Wiki setup failing

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#274]
```
Setting up wiki content...

PATCHDEMO='/var/www/html' NAME='1c3fa41ba8bbc5f4a399db1e622aaa37' MAINPAGE='This wiki was generated on [https://patchdemo.wmflabs.org Patch Demo] at ~~~~~.

;Branch: master
;Applied patches: (none)
;Linked tasks: (none)' USE_PROXY='' /var/www/html/new/postinstall.sh 2>&1
+ sleep 1
+ echo 'This wiki was generated on [https://patchdemo.wmflabs.org Patch Demo] at ~~~~~.

;Branch: master
;Applied patches: (none)
;Linked tasks: (none)'
+ php /var/www/html/wikis/1c3fa41ba8bbc5f4a399db1e622aaa37/w/maintenance/edit.php Main_Page
[43f8dd9293af571587f984de] [no req]   TypeError: Argument 1 passed to Wikimedia\Rdbms\TransactionProfiler::recordConnection() must be of the type string, null given, called in /srv/patchdemo-wikis/1c3fa41ba8bbc5f4a399db1e622aaa37/w/includes/libs/rdbms/loadbalancer/LoadBalancer.php on line 1006
Backtrace:
from /srv/patchdemo-wikis/1c3fa41ba8bbc5f4a399db1e622aaa37/w/includes/libs/rdbms/TransactionProfiler.php(197)
#0 /srv/patchdemo-wikis/1c3fa41ba8bbc5f4a399db1e622aaa37/w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(1006): Wikimedia\Rdbms\TransactionProfiler->recordConnection(NULL, string, boolean)
#1 /srv/patchdemo-wikis/1c3fa41ba8bbc5f4a399db1e622aaa37/w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(960): Wikimedia\Rdbms\LoadBalancer->getServerConnection(integer, string, integer)
#2 /srv/patchdemo-wikis/1c3fa41ba8bbc5f4a399db1e622aaa37/w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(1099): Wikimedia\Rdbms\LoadBalancer->getConnection(integer, array, string, integer)
#3 /srv/patchdemo-wikis/1c3fa41ba8bbc5f4a399db1e622aaa37/w/includes/user/User.php(819): Wikimedia\Rdbms\LoadBalancer->getConnectionRef(integer)
#4 /srv/patchdemo-wikis/1c3fa41ba8bbc5f4a399db1e622aaa37/w/maintenance/edit.php(64): User::newSystemUser(string, array)
#5 /srv/patchdemo-wikis/1c3fa41ba8bbc5f4a399db1e622aaa37/w/maintenance/doMaintenance.php(112): EditCLI->execute()
#6 /srv/patchdemo-wikis/1c3fa41ba8bbc5f4a399db1e622aaa37/w/maintenance/edit.php(134): require_once(string)
#7 {main}
PATCHDEMO='/var/www/html' WIKI='1c3fa41ba8bbc5f4a399db1e622aaa37' /var/www/html/deletewiki.sh 2>&1
+ rm -rf /var/www/html/wikis/1c3fa41ba8bbc5f4a399db1e622aaa37
+ mysql -u patchdemo --password=patchdemo -e 'DROP DATABASE IF EXISTS patchdemo_1c3fa41ba8bbc5f4a399db1e622aaa37'
Could not setup wiki content.
```

**Comment by edg2s** [comment]
I see you've already filed https://phabricator.wikimedia.org/T277056. I'll leave this open until upstream is fixed.

**Comment by MatmaRex** [comment]
Fixed
