### ISSUE TITLE
Exception thrown when trying to verify user

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#292]
```
| Fatal error:  Uncaught Symfony\Component\Yaml\Exception\ParseException: Duplicate key "experimental" detected at line 4774. in /var/www/html/vendor/symfony/yaml/Parser.php:338
| Stack trace:
| #0 /var/www/html/vendor/symfony/yaml/Parser.php(525): Symfony\Component\Yaml\Parser->doParse(Array, 0)
| #1 /var/www/html/vendor/symfony/yaml/Parser.php(196): Symfony\Component\Yaml\Parser->parseBlock(4727, 'name: mediawiki...', 0)
| #2 /var/www/html/vendor/symfony/yaml/Parser.php(525): Symfony\Component\Yaml\Parser->doParse('\n#### Continuou...', 0)
| #3 /var/www/html/vendor/symfony/yaml/Parser.php(320): Symfony\Component\Yaml\Parser->parseBlock(2013, '\n#### Continuou...', 0)
| #4 /var/www/html/vendor/symfony/yaml/Parser.php(96): Symfony\Component\Yaml\Parser->doParse(Array, 0)
| #5 /var/www/html/vendor/symfony/yaml/Yaml.php(80): Symfony\Component\Yaml\Parser->parse('# vim: set ts=2...', 0)
| #6 /var/www/html/includes.php(431): Symfony\Component\Yaml\Yaml::parse('# vim: set ts=2...')
| #7 /var/www/html/new.php(189): is_trusted_user('esanders@wikime. in /var/www/html/vendor/symfony/yaml/Parser.php on line 338
```

**Comment by edg2s** [comment]
Looks like a duplicate key in the wikibase section of the yaml file.

**Comment by edg2s** [comment]
Regression from https://github.com/wikimedia/integration-config/commit/07b0a1396517af03b0cc7d641d323d3a0f926f4a

Only triggers when patches aren't V+2

**Comment by edg2s** [comment]
Fixed by https://github.com/wikimedia/integration-config/commit/b1d64c80598715362c59941296226c2204e2921e
