### ISSUE TITLE
Wiki creation is failing

### ISSUE THREAD

**Issue by MatmaRex** [MatmaRex/patchdemo#311]
```
+ php /var/www/html/wikis/1b54dfc9eb/w/maintenance/createAndPromote.php Alice patchdemo1
[7517be596d29cdc9f7024e2a] [no req]   Error: Class 'Wikimedia\Equivset\Equivset' not found
Backtrace:
from /srv/patchdemo-wikis/1b54dfc9eb/w/extensions/AbuseFilter/includes/ServiceWiring.php(121)
#0 /srv/patchdemo-wikis/1b54dfc9eb/w/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer::{closure}(MediaWiki\MediaWikiServices)
#1 /srv/patchdemo-wikis/1b54dfc9eb/w/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService(string)
#2 /srv/patchdemo-wikis/1b54dfc9eb/w/includes/MediaWikiServices.php(279): Wikimedia\Services\ServiceContainer->getService(string)
#3 /srv/patchdemo-wikis/1b54dfc9eb/w/vendor/wikimedia/services/src/ServiceContainer.php(424): MediaWiki\MediaWikiServices->getService(string)
#4 /srv/patchdemo-wikis/1b54dfc9eb/w/extensions/AbuseFilter/includes/ServiceWiring.php(285): Wikimedia\Services\ServiceContainer->get(string)
#5 /srv/patchdemo-wikis/1b54dfc9eb/w/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer::{closure}(MediaWiki\MediaWikiServices)
#6 /srv/patchdemo-wikis/1b54dfc9eb/w/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService(string)
#7 /srv/patchdemo-wikis/1b54dfc9eb/w/includes/MediaWikiServices.php(279): Wikimedia\Services\ServiceContainer->getService(string)
#8 /srv/patchdemo-wikis/1b54dfc9eb/w/extensions/AbuseFilter/includes/AbuseFilterServices.php(211): MediaWiki\MediaWikiServices->getService(string)
#9 /srv/patchdemo-wikis/1b54dfc9eb/w/extensions/AbuseFilter/includes/AbuseFilterPreAuthenticationProvider.php(54): MediaWiki\Extension\AbuseFilter\AbuseFilterServices::getFilterRunnerFactory()
#10 /srv/patchdemo-wikis/1b54dfc9eb/w/extensions/AbuseFilter/includes/AbuseFilterPreAuthenticationProvider.php(33): MediaWiki\Extension\AbuseFilter\AbuseFilterPreAuthenticationProvider->testUser(User, User, boolean)
#11 /srv/patchdemo-wikis/1b54dfc9eb/w/includes/auth/AuthManager.php(1756): MediaWiki\Extension\AbuseFilter\AbuseFilterPreAuthenticationProvider->testUserForCreation(User, string, array)
#12 /srv/patchdemo-wikis/1b54dfc9eb/w/maintenance/createAndPromote.php(124): MediaWiki\Auth\AuthManager->autoCreateUser(User, string, boolean)
#13 /srv/patchdemo-wikis/1b54dfc9eb/w/maintenance/doMaintenance.php(108): CreateAndPromote->execute()
#14 /srv/patchdemo-wikis/1b54dfc9eb/w/maintenance/createAndPromote.php(166): require_once(string)
#15 {main}
PATCHDEMO='/var/www/html' WIKI='1b54dfc9eb' /var/www/html/deletewiki.sh 2>&1
+ rm -rf /var/www/html/wikis/1b54dfc9eb
+ mysql -u patchdemo --password=patchdemo -e 'DROP DATABASE IF EXISTS patchdemo_1b54dfc9eb'
Could not setup wiki content.
```

**Comment by MatmaRex** [comment]
Apparently AbuseFilter has Composer dependencies, and we're not installing them. I guess this error is caused by https://gerrit.wikimedia.org/r/c/mediawiki/extensions/AbuseFilter/+/716006, but AbuseFilter functionality on Patchdemo might have been broken silently for a while.
