### ISSUE TITLE
Wikis with DiscussionTools can't be created: "The text of the revision with ID 34 exceeds the maximum allowable size (100 KiB)"

### ISSUE THREAD

**Issue by MatmaRex** [MatmaRex/patchdemo#504]
```
+ echo 'Importing /var/www/html/pages/extensions-DiscussionTools.xml'
Importing /var/www/html/pages/extensions-DiscussionTools.xml
+ php /var/www/html/wikis/61d1136ca7/w/maintenance/importDump.php
MWException from line 1072 of /srv/patchdemo-wikis/61d1136ca7/w/includes/import/WikiImporter.php: The text of the revision with ID 34 exceeds the maximum allowable size (100 KiB)
#0 /srv/patchdemo-wikis/61d1136ca7/w/includes/import/WikiImporter.php(1105): WikiImporter->makeContent()
#1 /srv/patchdemo-wikis/61d1136ca7/w/includes/import/WikiImporter.php(1005): WikiImporter->processRevision()
#2 /srv/patchdemo-wikis/61d1136ca7/w/includes/import/WikiImporter.php(937): WikiImporter->handleRevision()
#3 /srv/patchdemo-wikis/61d1136ca7/w/includes/import/WikiImporter.php(755): WikiImporter->handlePage()
#4 /srv/patchdemo-wikis/61d1136ca7/w/maintenance/importDump.php(364): WikiImporter->doImport()
#5 /srv/patchdemo-wikis/61d1136ca7/w/maintenance/importDump.php(305): BackupReader->importFromHandle()
#6 /srv/patchdemo-wikis/61d1136ca7/w/maintenance/importDump.php(139): BackupReader->importFromStdin()
#7 /srv/patchdemo-wikis/61d1136ca7/w/maintenance/includes/MaintenanceRunner.php(309): BackupReader->execute()
#8 /srv/patchdemo-wikis/61d1136ca7/w/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#9 /srv/patchdemo-wikis/61d1136ca7/w/maintenance/importDump.php(369): require_once('/srv/patchdemo-...')
#10 {main}
```

**Comment by MatmaRex** [comment]
https://gerrit.wikimedia.org/r/c/mediawiki/extensions/GrowthExperiments/+/819161/9/tests/selenium/fixtures/GrowthExperiments.LocalSettings.php#17

**Comment by edg2s** [comment]
CC @tgr @kostajh

**Comment by kostajh** [comment]
https://gerrit.wikimedia.org/r/c/mediawiki/extensions/GrowthExperiments/+/841545

**Comment by MatmaRex** [comment]
That fixed it, thanks @kostajh!
