### ISSUE TITLE
Fatal error: Uncaught Error: Cannot access private property AutoLoader::$psr4Namespaces

### ISSUE THREAD

**Issue by MatmaRex** [MatmaRex/patchdemo#544]
```
Fatal error:  Uncaught Error: Cannot access private property AutoLoader::$psr4Namespaces in /srv/patchdemo-wikis/b4db406cc4/w/settings.d/services-parsoid.php:7
Stack trace:
#0 /srv/patchdemo-wikis/b4db406cc4/w/LocalSettings.php(216): include_once()
#1 /srv/patchdemo-wikis/b4db406cc4/w/includes/Setup.php(209): require_once('/srv/patchdemo-...')
#2 /srv/patchdemo-wikis/b4db406cc4/w/includes/WebStart.php(92): require_once('/srv/patchdemo-...')
#3 /srv/patchdemo-wikis/b4db406cc4/w/index.php(44): require('/srv/patchdemo-...')
#4 {main}
  thrown in /srv/patchdemo-wikis/b4db406cc4/w/settings.d/services-parsoid.php on line 7
```

**Comment by MatmaRex** [comment]
AutoLoader::$psr4Namespaces was made private in https://phabricator.wikimedia.org/T332930

The alternative is AutoLoader::registerNamespaces(): https://www.mediawiki.org/w/index.php?title=Parsoid&diff=prev&oldid=5222750
