### ISSUE TITLE
VE not loading on new demos

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#70]
http://patchdemo.wmflabs.org/wikis/b06eb2e7b02e28684e8e30dbc36c0585/w/index.php/Main_Page?veaction=edit

`Error contacting the Parsoid/RESTBase server (HTTP 500)`

**Comment by MatmaRex** [comment]
This is the HTTP 500 error: http://patchdemo.wmflabs.org/wikis/b06eb2e7b02e28684e8e30dbc36c0585/w/rest.php/localhost/v3/page/html/Main_Page

```
[2982220f6fd4a29e08865711] /wikis/b06eb2e7b02e28684e8e30dbc36c0585/w/rest.php/localhost/v3/page/html/Main_Page Error from line 94 of /var/www/html/wikis/b06eb2e7b02e28684e8e30dbc36c0585/w/parsoid/extension/src/Config/SiteConfig.php: Class 'MWParsoid\Config\ExtensionRegistry' not found

Backtrace:

#0 /var/www/html/wikis/b06eb2e7b02e28684e8e30dbc36c0585/w/parsoid/extension/ServiceWiring.php(19): MWParsoid\Config\SiteConfig->__construct()
#1 /var/www/html/wikis/b06eb2e7b02e28684e8e30dbc36c0585/w/includes/libs/services/ServiceContainer.php(451): Wikimedia\Services\ServiceContainer->{closure}(MediaWiki\MediaWikiServices)
#2 /var/www/html/wikis/b06eb2e7b02e28684e8e30dbc36c0585/w/includes/libs/services/ServiceContainer.php(419): Wikimedia\Services\ServiceContainer->createService(string)
#3 /var/www/html/wikis/b06eb2e7b02e28684e8e30dbc36c0585/w/includes/libs/services/ServiceContainer.php(427): Wikimedia\Services\ServiceContainer->getService(string)
#4 /var/www/html/wikis/b06eb2e7b02e28684e8e30dbc36c0585/w/parsoid/extension/src/ParsoidServices.php(22): Wikimedia\Services\ServiceContainer->get(string)
#5 /var/www/html/wikis/b06eb2e7b02e28684e8e30dbc36c0585/w/parsoid/extension/src/Rest/Handler/ParsoidHandler.php(82): MWParsoid\ParsoidServices->getParsoidSiteConfig()
#6 /var/www/html/wikis/b06eb2e7b02e28684e8e30dbc36c0585/w/vendor/wikimedia/object-factory/src/ObjectFactory.php(172): MWParsoid\Rest\Handler\ParsoidHandler::factory()
#7 /var/www/html/wikis/b06eb2e7b02e28684e8e30dbc36c0585/w/vendor/wikimedia/object-factory/src/ObjectFactory.php(102): Wikimedia\ObjectFactory::getObjectFromSpec(array, array)
#8 /var/www/html/wikis/b06eb2e7b02e28684e8e30dbc36c0585/w/includes/Rest/Router.php(336): Wikimedia\ObjectFactory->createObject(array)
#9 /var/www/html/wikis/b06eb2e7b02e28684e8e30dbc36c0585/w/includes/Rest/Router.php(317): MediaWiki\Rest\Router->createHandler(MediaWiki\Rest\RequestFromGlobals, array)
#10 /var/www/html/wikis/b06eb2e7b02e28684e8e30dbc36c0585/w/includes/Rest/EntryPoint.php(139): MediaWiki\Rest\Router->execute(MediaWiki\Rest\RequestFromGlobals)
#11 /var/www/html/wikis/b06eb2e7b02e28684e8e30dbc36c0585/w/includes/Rest/EntryPoint.php(106): MediaWiki\Rest\EntryPoint->execute()
#12 /var/www/html/wikis/b06eb2e7b02e28684e8e30dbc36c0585/w/rest.php(31): MediaWiki\Rest\EntryPoint::main()
#13 {main}
```

**Comment by MatmaRex** [comment]
Seems like a real bug in Parsoid, `use ExtensionRegistry` is missing in some places.

**Comment by MatmaRex** [comment]
Should be fixed by <https://gerrit.wikimedia.org/r/c/mediawiki/services/parsoid/+/601366>, try re-creating the demo after that merges.

**Comment by edg2s** [comment]
Verified.
